"""
MABE Detector — SPL Session Reference Builder
===============================================

Produces the Level 3 session reference: a Splunk search string that
retrieves all events for a flagged session. Injected into CorrelationAgent
as the session_ref_builder callable.

DESIGN
------
The session_ref field in CorrelationOutput is what an analyst clicks to
move from the alert into the raw event trail. In Splunk deployment it is
an SPL query string — not a file path (that's the SIFT specialization).

Two query variants are provided:

1. BASE — retrieves all events for the session, sorted by time.
   Always generated. Used as the session_ref in CorrelationOutput.

2. FOCUSED — retrieves the same events but highlights the fields most
   relevant to the fired mechanisms (e.g. adds a table command that
   surfaces dest, dest_port, action, app prominently for enumeration
   alerts). Generated by build_focused_spl() when the CorrelationOutput
   is available and used in the notable event's drilldown field.

The base variant is what the CorrelationAgent injects at correlation time
(it only has the session_id at that point). The focused variant is built
later in notable_event.py when the full CorrelationOutput is available.

SPLUNK MCP NOTE
---------------
These SPL strings are the same queries an analyst would run manually or
via the Splunk AI Assistant. They can also be passed to explain_spl or
optimize_spl in the MCP demo layer.
"""

from __future__ import annotations

DEFAULT_INDEX      = "mabe"
DEFAULT_SOURCETYPE = "mabe:*"


# ---------------------------------------------------------------------------
# SplRefBuilder
# ---------------------------------------------------------------------------

class SplRefBuilder:
    """
    Builds SPL session reference strings for CorrelationAgent injection.

    Parameters
    ----------
    index : str
        Splunk index name. Default: "mabe".
    sourcetype_filter : str
        Sourcetype filter. Default: "mabe:*".
    """

    def __init__(
        self,
        index: str = DEFAULT_INDEX,
        sourcetype_filter: str = DEFAULT_SOURCETYPE,
    ) -> None:
        self._index = index
        self._sourcetype = sourcetype_filter

    def build(self, session_id: str) -> str:
        """
        Build the base session reference SPL for a given session ID.

        This is the callable injected into CorrelationAgent:
            agent = CorrelationAgent(session_ref_builder=builder.build)

        Parameters
        ----------
        session_id : str

        Returns
        -------
        str
            SPL query retrieving all events for this session, time-sorted.
        """
        safe_sid = _escape_spl_string(session_id)
        return (
            f'index={self._index} sourcetype={self._sourcetype}'
            f' mabe_session_id="{safe_sid}"'
            f' | sort _time'
            f' | table _time src dest dest_port user action app'
            f'   sourcetype mabe_event_type mabe_session_id'
        )

    def build_focused(
        self,
        session_id: str,
        mechanisms_fired: list[str],
    ) -> str:
        """
        Build a focused session reference SPL that surfaces the fields
        most relevant to the mechanisms that fired.

        Used in the notable event's drilldown field where the full
        CorrelationOutput is available.

        Parameters
        ----------
        session_id : str
        mechanisms_fired : list[str]
            mechanism_ids that produced fired=True output.
            e.g. ["velocity", "enumeration"]

        Returns
        -------
        str
            SPL query with mechanism-appropriate field ordering and
            eval annotations.
        """
        safe_sid = _escape_spl_string(session_id)

        base = (
            f'index={self._index} sourcetype={self._sourcetype}'
            f' mabe_session_id="{safe_sid}"'
            f' | sort _time'
        )

        # Build a table command that prioritises relevant fields
        # based on which mechanisms fired
        table_fields = ["_time", "user", "src", "dest", "dest_port",
                        "action", "app", "mabe_event_type"]

        evals: list[str] = []

        if "velocity" in mechanisms_fired:
            # Add inter-event gap computation for velocity drill-down
            evals.append(
                "eval _prev_time=prev(_time)"
            )
            evals.append(
                "eval gap_ms=round((_time - strptime(_prev_time,"
                ' "%Y-%m-%dT%H:%M:%S.%3N%Z")) * 1000, 0)'
            )
            table_fields.insert(2, "gap_ms")

        if "enumeration" in mechanisms_fired:
            # Surface dest_port prominently — needed for node type inference
            if "dest_port" not in table_fields[:4]:
                table_fields.insert(4, "dest_port")

        if "priv_escalation" in mechanisms_fired:
            # Filter to auth and file access events for priv esc drill-down
            base += (
                f' | where mabe_event_type="auth_attempt"'
                f' OR mabe_event_type="file_access"'
                f' OR mabe_event_type="kerberos_tgt_request"'
            )

        # Deduplicate while preserving order
        seen: set[str] = set()
        unique_fields: list[str] = []
        for f in table_fields:
            if f not in seen:
                seen.add(f)
                unique_fields.append(f)

        eval_clause = ""
        if evals:
            eval_clause = " | " + " | ".join(evals)

        table_clause = " | table " + " ".join(unique_fields)

        return base + eval_clause + table_clause


# ---------------------------------------------------------------------------
# Module-level convenience function
# ---------------------------------------------------------------------------

def make_session_ref_builder(
    index: str = DEFAULT_INDEX,
    sourcetype_filter: str = DEFAULT_SOURCETYPE,
) -> callable:
    """
    Return the session_ref_builder callable for CorrelationAgent injection.

    Usage:
        from splunk.output.spl_ref_builder import make_session_ref_builder

        agent = CorrelationAgent(
            alert_threshold_override=0.60,
            session_ref_builder=make_session_ref_builder(),
        )

    Parameters
    ----------
    index : str
    sourcetype_filter : str

    Returns
    -------
    callable
        Function (session_id: str) -> str
    """
    builder = SplRefBuilder(index=index, sourcetype_filter=sourcetype_filter)
    return builder.build


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def _escape_spl_string(value: str) -> str:
    """Escape double quotes in a string for safe SPL embedding."""
    return value.replace('"', '\\"')
